name: api
description: Flarum Restfull Api of Dart
version: 0.0.1
author: "flarum-flutter"
homepage: "https://github.com/flarum-flutter/api"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter